### ISSUE TITLE
investigate skills-deploy pipeline failure

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-client#23]
```
FAIL test/display/SkillsLevelJS.test.js
  ● Console

    console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Error: connect ECONNREFUSED 127.0.0.1:80
          at Object.dispatchError (/builds/skills/skills-deploy/skills-client-import/skills-client-js/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
          at Request.<anonymous> (/builds/skills/skills-deploy/skills-client-import/skills-client-js/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
          at Request.emit (events.js:327:22)
          at Request.onRequestError (/builds/skills/skills-deploy/skills-client-import/skills-client-js/node_modules/request/request.js:877:8)
          at ClientRequest.emit (events.js:315:20)
          at Socket.socketErrorListener (_http_client.js:426:9)
          at Socket.emit (events.js:315:20)
          at emitErrorNT (internal/streams/destroy.js:92:8)
          at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
          at processTicksAndRejections (internal/process/task_queues.js:84:21) undefined

  ● SkillsLevelJS › update - SkillsReporter event handler › updates this.skillLevel to highest level attained from event

    Unable to report skillsClientVersion

      34 |     if (xhr.readyState === 4) {
      35 |       if (xhr.status !== 200) {
    > 36 |         reject(new Error('Unable to report skillsClientVersion'));
         |                ^
      37 |       } else {
      38 |         resolve(JSON.parse(xhr.response));
      39 |       }

      at XMLHttpRequest.xhr.onreadystatechange (src/config/SkillsConfiguration.js:36:16)
      at XMLHttpRequest.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:33:32)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at XMLHttpRequestEventTargetImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at XMLHttpRequestEventTargetImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at XMLHttpRequest.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at requestErrorSteps (node_modules/jsdom/lib/jsdom/living/xhr-utils.js:121:7)
      at Object.dispatchError (node_modules/jsdom/lib/jsdom/living/xhr-utils.js:62:3)
      at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
      at Request.onRequestError (node_modules/request/request.js:877:8)
```

**Comment by rmmayo** [comment]
pushed directly to master
